"""Evidence-linked report scaffold: measurements are actual, interpretations are bounded."""
import re
from .analysis import CONDITIONS

IR_DISCUSSION = """Zipf’s Law matters to an information retrieval system because term usage is highly uneven. A small group of words accounts for many token occurrences, while a long tail contains numerous rare terms. This empirical pattern helps explain engineering choices, but it should not be treated as an exact universal distribution or as a guarantee of retrieval quality.

First, stopword handling is a trade-off. Frequent function words may occur in most documents, so their presence often provides little evidence for distinguishing relevant articles from unrelated ones. Removing these terms can reduce token volume and shorten large postings lists. However, frequency alone does not make a word useless: phrases, negation, and particular information needs may depend on common words. Comparing conditions B and C on the same abstracts makes the storage and vocabulary effects observable. It does not measure retrieval effectiveness; that would require relevance judgments and evaluation metrics such as precision or recall.

Second, the inverted index has two related costs. The dictionary stores unique terms, including a large number of rare spellings, technical expressions, and inflected forms. Postings lists store the documents containing each term, together with information such as term frequency. A frequent term repeated in one abstract raises CF without adding many document IDs, whereas a term spread across many abstracts raises DF and generally creates a longer postings list. Stopword removal primarily reduces ubiquitous postings, while stemming can merge dictionary entries and their postings. Compression methods such as gap encoding benefit from sorted document IDs; actual space savings must be measured rather than inferred from the Zipf exponent alone.

Third, TF-IDF combines within-document frequency with collection-wide rarity. IDF equals ln(N/DF) in this experiment. A word appearing in every document has IDF zero, regardless of its CF. A repeated technical term in only a few documents can receive higher IDF, although rarity does not automatically imply relevance. The CF/DF table therefore provides a more useful explanation than a frequency ranking alone.

Finally, an approximate law is still useful as a planning model. It suggests where memory, indexing effort, and query processing time may concentrate, and motivates testing preprocessing choices. Regional residuals, vocabulary changes, and comparisons between domains reveal where the approximation breaks down. These observations connect a textbook regularity to measurable design decisions without turning a high regression R² into proof."""

def number(value):
    return 'undefined' if value is None else f'{value:.4f}'

def report(analyses, condition='D'):
    selected=analyses[condition]
    fit=selected['fit']; rows=selected['rows']
    regions=[r for r in selected['regions'] if r['global_rmse'] is not None and r['terms']>=2]
    best=min(regions,key=lambda r:r['global_rmse']) if regions else None
    broad=max(rows,key=lambda r:r['df']) if rows else None
    concentrated=max(rows,key=lambda r:r['cf']/r['df']) if rows else None
    answers=[
        ('RQ1 / Q1: Does this collection follow Zipf’s Law?',f"The {selected['documents']} analyzed abstracts show a rank-frequency distribution with R²={number(fit['r2'])} and log-space RMSE={number(fit['rmse'])}. These values describe an approximate fit, not proof of a power law. Inspect curvature, residuals and frequency plateaus before judging how closely the corpus follows Zipf."),
        ('RQ2 / Q2: What is the empirical exponent?',f"Condition {condition}: k={number(fit['exponent'])}; slope={number(fit['slope'])}; intercept={number(fit['intercept'])}. OLS uses every term rank and natural logs. k is the negative slope; compare it with the idealized reference 1 without assuming it must equal 1."),
        ('Q3: Is R² sufficient?',"No. Logged monotone frequency data can have a high R² without being generated by a power law. Residual curvature, a long tied singleton tail, sample size, preprocessing, and comparison with alternative distributions all matter. This app does not perform a formal power-law goodness-of-fit test."),
        ('Q4: Which portion fits best?',f"The smallest error against the overall fitted line occurs in {best['name']} (RMSE={number(best['global_rmse'])}). Regional boundaries are rank-based (first 5%, 5–50%, last 50%). Compare local R² and exponent too; a flat region has undefined R²." if best else "There are too few terms for a meaningful regional comparison."),
        ('RQ3: How does preprocessing change the distribution?', ' → '.join(f"{k}: vocabulary {analyses[k]['vocabulary']}, k {number(analyses[k]['fit']['exponent'])}, leading terms {', '.join(analyses[k]['top_terms'])}" for k in CONDITIONS)+'. All conditions use identical document rows. A and B coincide because HW1 tokenization already excludes standalone punctuation; B→C removes stopwords; C→D merges Porter stems. Use the four curves to assess shape changes instead of assuming a direction.'),
        ('RQ4 / CF vs DF: Why can high CF coexist with low DF?',f"CF counts every occurrence; DF counts a document once. Repetition within a few documents increases CF without broad coverage. In this corpus, “{concentrated['term']}” has CF={concentrated['cf']}, DF={concentrated['df']} and CF/DF={concentrated['cf']/concentrated['df']:.2f}. “{broad['term']}” appears in {broad['df']} of {selected['documents']} abstracts. DF measures distribution across documents, while CF reflects token volume." if rows else 'Import abstracts to calculate CF and DF.'),
        ('TF-IDF: Why do common terms receive lower IDF?',"IDF depends on DF, not CF directly. Terms occurring in nearly every document have ln(N/DF) near zero. Zipf describes occurrence frequency; common terms often also have broad coverage, but the two quantities must be checked empirically. Per-document TF × IDF is shown separately below."),
        ('RQ5 / Final Challenge: Why is an approximate law still useful?',"A useful empirical approximation predicts uneven dictionary and postings costs and motivates preprocessing experiments. It need not be exact to guide index design. Its value is a testable engineering expectation; the observed residuals and domain differences define its limits. Retrieval quality still needs an independent relevance evaluation."),
    ]
    summary=[f"The analyzed scope contains {selected['documents']} abstracts, with {selected['tokens']} tokens and {selected['vocabulary']} unique terms under condition {condition}. The target is approximately 1,000 abstracts; smaller collections are preliminary.",f"The fitted exponent is k={number(fit['exponent'])}; R²={number(fit['r2'])}; log-space RMSE={number(fit['rmse'])}. The data support a descriptive approximation, not a proof of a universal law. The best regional match is {best['name'] if best else 'not measurable'}.",f"Vocabulary sizes across A/B/C/D are { '/'.join(str(analyses[k]['vocabulary']) for k in CONDITIONS)}. Stopword removal and stemming change both the vocabulary and the curve; their effect is observable on these exact documents, rather than inferred from the textbook.","CF and DF separate repetition from coverage. IDF downweights broadly distributed words. The experiment links the long frequency tail to dictionary size and frequent terms to long postings lists, while showing that fit quality and retrieval effectiveness are different questions."]
    return {'answers':answers,'discussion':IR_DISCUSSION,'discussion_words':len(IR_DISCUSSION.split()),'summary':summary,'best_region':best}

def markdown(analyses,condition,scope):
    content=report(analyses,condition)
    sections=['# Zipf research report',f'Scope: {scope}', 'Interpretations below are evidence-linked draft text; review against plots and course material.']
    sections += ['## '+title+'\n\n'+answer for title,answer in content['answers']]
    sections += [f"## Information Retrieval implications ({content['discussion_words']} words)\n\n"+content['discussion'],'## One-page executive summary\n\n'+'\n\n'.join(content['summary'])]
    return '\n\n'.join(sections)
