# Generated by Django 5.1.6 on 2026-09-14 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('source_file', models.CharField(max_length=300)),
                ('raw_text', models.TextField()),
                ('char_count', models.IntegerField(default=0)),
                ('word_count', models.IntegerField(default=0)),
                ('sentence_count', models.IntegerField(default=0)),
                ('indexed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_freq', models.IntegerField(default=1)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='search.document')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='search.term')),
            ],
            options={
                'indexes': [models.Index(fields=['term', 'document'], name='search_post_term_id_55d212_idx')],
                'unique_together': {('term', 'document')},
            },
        ),
    ]
