# Generated by Django 5.2.17 on 2026-10-01 03:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_document_pmid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('key', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='documents', to='search.topic'),
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested', models.PositiveIntegerField()),
                ('status', models.CharField(default='queued', max_length=20)),
                ('imported', models.PositiveIntegerField(default=0)),
                ('linked', models.PositiveIntegerField(default=0)),
                ('duplicates', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('examined', models.PositiveIntegerField(default=0)),
                ('available', models.PositiveIntegerField(default=0)),
                ('offset', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='search.topic')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(models.Value(1), condition=models.Q(('status__in', ['queued', 'running'])), name='one_active_topic_import')],
            },
        ),
    ]
