# Generated by Django 5.2.17 on 2026-10-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_topic_document_topics_importjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='arxiv_id',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='importjob',
            name='source',
            field=models.CharField(choices=[('pubmed', 'PubMed'), ('arxiv', 'arXiv CS')], default='pubmed', max_length=20),
        ),
    ]
